Update android support + Fix issue with nested fragments
java.lang.RuntimeException: Unable to start activity
ComponentInfo{com.github.devnied.emvnfccard/com.github.devnied.emvnfccar
d.activity.HomeActivity}: java.lang.IllegalArgumentException: No view
found for id 0x7f0c0007
(com.github.devnied.emvnfccard:id/about_inapp_content) for fragment
BillingFragment{41c71280 #1 id=0x7f0c0007}
at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:248
3)
at
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2535
)
at android.app.ActivityThread.access$600(ActivityThread.java:178)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1390)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5560)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.ja
va:844)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: No view found for id
0x7f0c0007 (com.github.devnied.emvnfccard:id/about_inapp_content) for
fragment BillingFragment{41c71280 #1 id=0x7f0c0007}
at
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.j
ava:934)
at
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.j
ava:1121)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
at
android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentMa
nager.java:1484)
at
android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:57
1)
at
android.app.Instrumentation.callActivityOnStart(Instrumentation.java:123
7)
at android.app.Activity.performStart(Activity.java:5145)
at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:244
6)
... 11 more